version: '3'

services:
  db:
    container_name: "courses"
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    ports:
      - 5437:5432
volumes:
  db_data: